export const CURRENT_YEAR = new Date().getUTCFullYear();

export interface PlatformArticle {
  slug: string;
  platform: string;
  sourcePath: string;
  exampleUrl: string;
  description: string;
  introduction: string;
  extracts: string[];
  aiUseCases: string[];
  boundaries: string[];
  keywords: string[];
}

export const platformArticles: PlatformArticle[] = [
  {
    slug: 'scrape-amazon-data',
    platform: 'Amazon',
    sourcePath: '/amazon/',
    exampleUrl: 'https://www.amazon.de/echo-dot-2022/dp/B09B8X9RGM',
    description: `How to extract public Amazon product and search data for AI applications in ${CURRENT_YEAR} using one cacheable GET request.`,
    introduction: 'Amazon product and search pages contain useful facts alongside navigation, recommendations, account controls, and personalized storefront content. Focused extraction keeps the public product details or search result cards and removes most of that surrounding noise.',
    extracts: ['Product titles and canonical URLs', 'Public price, rating, availability, and image when present', 'Up to 20 normalized items from one search page', 'Product descriptions and visible specifications on exact product pages'],
    aiUseCases: ['Product research assistants', 'RAG indexes for public catalogs', 'Catalog normalization and enrichment', 'LLM-ready competitive research'],
    boundaries: ['Exact product pages and search URLs containing a query receive specialized extraction.', 'Search feeds are capped at 20 products; category browsing, pagination, carts, accounts, reviews, and personalized offers are unavailable.', 'Prices and availability can change and may be cached for up to one hour.'],
    keywords: ['Amazon scraper API', 'Amazon search API', 'Amazon product data API', 'AI product extraction', 'Amazon data for LLM', 'RAG ecommerce data'],
  },
  {
    slug: 'scrape-app-store-data',
    platform: 'App Store',
    sourcePath: '/app-store/',
    exampleUrl: 'https://apps.apple.com/us/app/chatgpt/id6448311069',
    description: `How to extract public Apple App Store app metadata for AI agents and product pipelines in ${CURRENT_YEAR}.`,
    introduction: 'App Store listings combine product facts with a large interactive storefront. A normalized software product entity keeps the public app identity, developer, description, price, rating, release details, icon, and screenshots in a predictable format.',
    extracts: ['App name, numeric ID, developer, and canonical URL', 'Integer minor-unit price and display price', 'Rating, rating count, category, version, and operating-system requirement', 'Public app icon, screenshots, description, and release notes'],
    aiUseCases: ['App research and discovery agents', 'Software catalog enrichment', 'App intelligence RAG pipelines', 'Cross-store product normalization'],
    boundaries: ['Only exact public app detail URLs are supported.', 'Search results, charts, reviews, account data, and app binaries are not included.', 'Availability and prices can vary by country and results may be cached for up to one hour.'],
    keywords: ['App Store scraper API', 'Apple app metadata API', 'App Store data for AI', 'mobile app RAG', 'AI app intelligence'],
  },
  {
    slug: 'scrape-bluesky-data',
    platform: 'Bluesky',
    sourcePath: '/bluesky/',
    exampleUrl: 'https://bsky.app/profile/bsky.app',
    description: `How to extract public Bluesky profiles and posts for AI agents and data pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Bluesky has distinct profile and post URLs. Converting both into the same response shape makes the content easier to search, summarize, and combine with other public sources.',
    extracts: ['Public profile details', 'Recent public profile posts as feed items', 'Individual public post text and authorship', 'Canonical links and timestamps when available'],
    aiUseCases: ['Public conversation monitoring', 'AI research agents', 'Semantic search over public posts', 'RAG datasets with source attribution'],
    boundaries: ['Private and deleted content is unavailable.', 'Replies and parent threads are not included.', 'Quoted or embedded content may be summarized rather than expanded completely.'],
    keywords: ['Bluesky scraper API', 'Bluesky data extraction', 'Bluesky API for AI', 'social data RAG', 'AI agent web data'],
  },
  {
    slug: 'scrape-google-news-data',
    platform: 'Google News',
    sourcePath: '/google-news/',
    exampleUrl: 'https://news.google.com/search?q=Cloudflare&hl=en-US&gl=US&ceid=US%3Aen',
    description: `How to extract public Google News searches, topics, and top stories for AI agents and RAG pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Google News groups current reporting from many publishers, but its browser interface is not a stable ingestion format. A normalized article feed keeps the public title, publisher, date, summary, and source link in a predictable shape for downstream systems.',
    extracts: ['Up to 50 public article results per page', 'Article titles, publishers, and publisher URLs when available', 'Publication timestamps and public summaries', 'Source-linked article entities in one normalized feed'],
    aiUseCases: ['Current-events research agents', 'Source discovery for RAG pipelines', 'Publisher and topic monitoring', 'News classification and enrichment'],
    boundaries: ['Search, topic, and top-stories pages are supported; personalized For You results are unavailable.', 'The result contains public metadata and summaries, not the full publisher article body.', 'Google Search and Google Shopping are separate products and are not included.'],
    keywords: ['Google News scraper API', 'Google News extraction API', 'Google News data for AI', 'news RAG pipeline', 'AI news extraction'],
  },
  {
    slug: 'scrape-google-play-data',
    platform: 'Google Play',
    sourcePath: '/google-play/',
    exampleUrl: 'https://play.google.com/store/apps/details?id=com.openai.chatgpt',
    description: `How to extract public Google Play app metadata for AI agents and product pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Google Play app pages expose useful public product metadata alongside an interactive storefront. Normalization turns an ordinary app URL into one consistent software product with developer, price, rating, description, icon, and screenshots.',
    extracts: ['App name, package ID, developer, and canonical URL', 'Integer minor-unit price and display price', 'Rating, rating count, category, operating system, and content rating', 'Public app icon, screenshots, and full listing description'],
    aiUseCases: ['Android app discovery agents', 'Software catalog enrichment', 'App market RAG pipelines', 'Cross-store product comparison'],
    boundaries: ['Only exact public app detail URLs are supported.', 'Search results, categories, reviews, account data, and APK downloads are not included.', 'Availability and prices can vary by country and results may be cached for up to one hour.'],
    keywords: ['Google Play scraper API', 'Google Play app metadata API', 'Google Play data for AI', 'Android app RAG', 'AI app intelligence'],
  },
  {
    slug: 'scrape-instagram-data',
    platform: 'Instagram',
    sourcePath: '/instagram/',
    exampleUrl: 'https://www.instagram.com/instagram/',
    description: `How to extract public Instagram posts, reels, and profiles for AI workflows in ${CURRENT_YEAR}.`,
    introduction: 'Public Instagram pages are visually rich, but AI systems usually need compact text, authorship, dates, and links. Normalization turns supported public posts and profiles into predictable Markdown or JSON without returning active embeds.',
    extracts: ['Public post and reel captions when exposed', 'Public account names and handles', 'Recent public profile posts', 'Media type, timestamps, and canonical links when available'],
    aiUseCases: ['Brand and creator research', 'AI-assisted content analysis', 'Public social knowledge bases', 'Cross-platform RAG ingestion'],
    boundaries: ['Private, deleted, login-only, and age-gated content is unavailable.', 'Stories, comments, transcripts, and media downloads are not included.', 'The public source can sometimes expose only minimal post metadata.'],
    keywords: ['Instagram scraper API', 'Instagram data for AI', 'Instagram post extraction', 'Instagram RAG pipeline', 'AI social media data'],
  },
  {
    slug: 'scrape-mastodon-data',
    platform: 'Mastodon',
    sourcePath: '/mastodon/',
    exampleUrl: 'https://mastodon.social/@trwnh/99664077509711321',
    description: `How to extract public Mastodon posts from federated instances for AI and RAG workflows in ${CURRENT_YEAR}.`,
    introduction: 'Mastodon is distributed across many independently operated instances, but compatible public status pages share a common structure. Normalization gives AI systems one predictable document shape without requiring instance-specific client code.',
    extracts: ['Public status text and canonical link', 'Display name and federated account handle', 'Publication timestamp and content warning', 'Media descriptions supplied by the author'],
    aiUseCases: ['Federated social research', 'Public-interest monitoring', 'Source-linked RAG collections', 'Cross-network AI analysis'],
    boundaries: ['Private, followers-only, deleted, and unavailable statuses are not accessible.', 'Timelines, complete threads, replies, and media downloads are not included.', 'Instances must expose compatible public endpoints.'],
    keywords: ['Mastodon scraper API', 'Fediverse data extraction', 'Mastodon data for AI', 'Mastodon RAG pipeline', 'federated social data'],
  },
  {
    slug: 'scrape-reddit-data',
    platform: 'Reddit',
    sourcePath: '/reddit/',
    exampleUrl: 'https://www.reddit.com/r/CloudFlare/',
    description: `How to extract public Reddit posts, communities, and profiles for AI and RAG pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Reddit pages mix post content with voting controls, navigation, recommendations, and long comment trees. A normalized extraction is useful when the goal is the public post or a compact community feed rather than a complete discussion archive.',
    extracts: ['Public post titles and bodies', 'Public subreddit and community feeds', 'Public user profile feeds', 'Authors, timestamps, and canonical URLs when available'],
    aiUseCases: ['Topic and community research', 'AI trend analysis', 'Public feedback summarization', 'Source-linked RAG collections'],
    boundaries: ['Private and quarantined communities are unsupported.', 'Complete comment trees are not included.', 'Deleted or restricted posts cannot be recovered.'],
    keywords: ['Reddit scraper API', 'Reddit data extraction', 'Reddit API for AI', 'Reddit RAG data', 'AI community research'],
  },
  {
    slug: 'scrape-shopify-data',
    platform: 'Shopify',
    sourcePath: '/shopify/',
    exampleUrl: 'https://www.allbirds.com/products/mens-cruiser-shadow-blue-natural-white-sole',
    description: `How to extract public Shopify product and catalog data for AI applications in ${CURRENT_YEAR}.`,
    introduction: 'Shopify storefront themes vary widely even though their public products share common concepts. Returning a consistent product entity or catalog feed removes theme-specific presentation from downstream AI and data work.',
    extracts: ['Public product titles and descriptions', 'Variants, prices, and product links when available', 'Public collection and storefront catalogs', 'Up to 50 normalized catalog items per feed'],
    aiUseCases: ['Commerce assistants and product search', 'Catalog RAG systems', 'Public market and assortment research', 'Cross-store product normalization'],
    boundaries: ['Stores can disable or protect public product data.', 'Checkout, customer, order, and administrative data is unavailable.', 'Catalog feeds are capped at 50 products.'],
    keywords: ['Shopify scraper API', 'Shopify products JSON API', 'Shopify data for AI', 'ecommerce RAG', 'AI catalog extraction'],
  },
  {
    slug: 'scrape-soundcloud-data',
    platform: 'SoundCloud',
    sourcePath: '/soundcloud/',
    exampleUrl: 'https://soundcloud.com/forss/flickermood',
    description: `How to extract public SoundCloud track, playlist, and creator metadata for AI workflows in ${CURRENT_YEAR}.`,
    introduction: 'SoundCloud pages center an interactive audio player, while many AI workflows only need the public title, creator, description, artwork, type, and source URL. A compact audio or profile entity is easier to index and attribute.',
    extracts: ['Public track, playlist, set, or profile title', 'Creator identity and public description', 'Artwork and content type when available', 'Canonical source link'],
    aiUseCases: ['Audio discovery assistants', 'Music and creator research', 'Metadata-based recommendation pipelines', 'Source catalogs for multimodal RAG'],
    boundaries: ['Private and deleted audio is unavailable.', 'Comments, waveforms, transcripts, and media downloads are not included.', 'The extractor does not analyze the recording itself.'],
    keywords: ['SoundCloud scraper API', 'SoundCloud metadata extraction', 'SoundCloud data for AI', 'audio RAG pipeline', 'AI music research'],
  },
  {
    slug: 'scrape-spotify-data',
    platform: 'Spotify',
    sourcePath: '/spotify/',
    exampleUrl: 'https://open.spotify.com/episode/7makk4oTQel546B0PZlDM5',
    description: `How to extract public Spotify music and podcast metadata for AI and RAG applications in ${CURRENT_YEAR}.`,
    introduction: 'Spotify links can represent tracks, albums, artists, playlists, podcast shows, or episodes. Converting supported public links into a consistent document makes them easier to classify and connect with other knowledge sources.',
    extracts: ['Public title and content type', 'Artwork and source URL when available', 'Tracks, albums, artists, playlists, shows, and episodes', 'One normalized Markdown or JSON document'],
    aiUseCases: ['Music and podcast discovery agents', 'Media knowledge graphs', 'Public metadata enrichment', 'Multimodal RAG source catalogs'],
    boundaries: ['Private and unavailable content is not accessible.', 'Lyrics, transcripts, playback data, audio analysis, and media downloads are not included.', 'Metadata completeness depends on the public fields Spotify exposes.'],
    keywords: ['Spotify scraper API', 'Spotify metadata extraction', 'Spotify data for AI', 'podcast RAG pipeline', 'AI music data'],
  },
  {
    slug: 'scrape-tiktok-data',
    platform: 'TikTok',
    sourcePath: '/tiktok/',
    exampleUrl: 'https://www.tiktok.com/@scout2015/video/6718335390845095173',
    description: `How to extract public TikTok posts and profiles for AI agents and RAG workflows in ${CURRENT_YEAR}.`,
    introduction: 'TikTok is video-first, but its public pages can still provide useful textual context such as captions, creator identity, dates, hashtags, and sound attribution. That metadata is often enough for discovery and AI classification without downloading media.',
    extracts: ['Public video and photo-post captions', 'Creator names and handles', 'Dates, hashtags, duration, and sound details when available', 'Public creator profile details'],
    aiUseCases: ['AI content discovery', 'Public trend classification', 'Creator research workflows', 'Cross-platform social RAG'],
    boundaries: ['Private, deleted, login-only, and age-restricted content is unavailable.', 'Comments, transcripts, and media downloads are not included.', 'Profile extraction does not provide a complete posting history.'],
    keywords: ['TikTok scraper API', 'TikTok data extraction 2026', 'TikTok data for AI', 'TikTok RAG pipeline', 'AI trend data'],
  },
  {
    slug: 'scrape-vimeo-data',
    platform: 'Vimeo',
    sourcePath: '/vimeo/',
    exampleUrl: 'https://vimeo.com/286898202',
    description: `How to extract public Vimeo video metadata for AI agents and data pipelines in ${CURRENT_YEAR}.`,
    introduction: 'A Vimeo video page combines playback with creator and presentation controls. For search, cataloging, and AI ingestion, the public title, author, description, date, duration, thumbnail, and source URL are usually the useful layer.',
    extracts: ['Public video title and description', 'Author and upload date when available', 'Duration and thumbnail', 'Canonical Vimeo source link'],
    aiUseCases: ['Video discovery agents', 'Public media catalogs', 'Metadata classification and enrichment', 'Multimodal RAG source indexes'],
    boundaries: ['Private and embed-disabled videos are unavailable.', 'Transcripts, captions, comments, and media downloads are not included.', 'The result describes the video rather than analyzing its audiovisual content.'],
    keywords: ['Vimeo scraper API', 'Vimeo metadata extraction', 'Vimeo data for AI', 'video RAG pipeline', 'AI video catalog'],
  },
  {
    slug: 'scrape-x-data',
    platform: 'X',
    sourcePath: '/x/',
    exampleUrl: 'https://x.com/jack/status/20',
    description: `How to extract public X posts as clean data for AI applications and agents in ${CURRENT_YEAR}.`,
    introduction: 'A public X status URL can be useful evidence for an AI workflow, but the surrounding interface is not. A post entity keeps the text, author, date when available, and original link in a reusable representation.',
    extracts: ['Public post text', 'Public author information', 'Canonical status links', 'Publication timestamps when available'],
    aiUseCases: ['AI research with source links', 'Public announcement monitoring', 'Knowledge-base ingestion', 'Cross-platform content normalization'],
    boundaries: ['Only individual public status URLs are supported.', 'Private, deleted, and age-gated posts are unavailable.', 'Timelines, search results, replies, and complete threads are not included.'],
    keywords: ['X scraper API', 'Twitter scraper API', 'X data for AI', 'tweet extraction API', 'social RAG pipeline'],
  },
  {
    slug: 'scrape-youtube-data',
    platform: 'YouTube',
    sourcePath: '/youtube/',
    exampleUrl: 'https://www.youtube.com/@Cloudflare',
    description: `How to extract public YouTube metadata, channels, and playlists for AI pipelines in ${CURRENT_YEAR}.`,
    introduction: 'YouTube pages provide valuable public metadata even when a workflow does not need the media itself. Normalized video and channel results make titles, descriptions, authors, dates, and links easier to index and combine with other sources.',
    extracts: ['Public video titles and descriptions', 'Channel and playlist feeds', 'Author, publication date, and canonical URL', 'Normalized Markdown or JSON metadata'],
    aiUseCases: ['Video discovery agents', 'AI research indexes', 'Metadata-based topic classification', 'Source catalogs for multimodal pipelines'],
    boundaries: ['Private, removed, member-only, and age-gated content is unavailable.', 'Transcripts, captions, spoken content, and media downloads are not included.', 'Results describe public videos; they do not analyze the audiovisual content.'],
    keywords: ['YouTube scraper API', 'YouTube metadata API', 'YouTube data for AI', 'video RAG pipeline', 'AI video research'],
  },
];

export interface AlternativePage {
  slug: string;
  provider: string;
  officialUrl: string;
  description: string;
  providerStrength: string;
  chooseProvider: string[];
  chooseExtractor: string[];
  keywords: string[];
}

export const alternativePages: AlternativePage[] = [
  {
    slug: 'scrapingbee',
    provider: 'ScrapingBee',
    officialUrl: 'https://www.scrapingbee.com/',
    description: 'Compare extractor.sh with ScrapingBee for public URL extraction, Markdown, JSON, AI agents, and RAG ingestion.',
    providerStrength: 'ScrapingBee is a broad scraping API with JavaScript rendering, proxy options, screenshots, selectors, and AI extraction controls.',
    chooseProvider: ['You need proxy selection or geotargeting.', 'You need browser interactions, screenshots, or selector-level controls.', 'You need a broad scraping infrastructure product.'],
    chooseExtractor: ['You want one cacheable GET URL.', 'You primarily need clean Markdown or normalized JSON.', 'You are feeding public pages into AI agents, search, or RAG.'],
    keywords: ['ScrapingBee alternative', 'ScrapingBee alternative for AI', 'Markdown scraping API', 'RAG web extraction API'],
  },
  {
    slug: 'firecrawl',
    provider: 'Firecrawl',
    officialUrl: 'https://www.firecrawl.dev/',
    description: 'Compare extractor.sh with Firecrawl for single-page extraction, AI-ready Markdown, crawling, and RAG workflows.',
    providerStrength: 'Firecrawl combines single-page scraping with crawling, mapping, screenshots, structured extraction, and other website-scale workflows.',
    chooseProvider: ['You need to crawl or map an entire website.', 'You need screenshots, actions, change tracking, or schema-driven extraction.', 'You want a broader ingestion platform.'],
    chooseExtractor: ['You need one public URL at a time.', 'A GET-only cache key fits your architecture.', 'You want normalized handling for supported social and commerce pages.'],
    keywords: ['Firecrawl alternative', 'Firecrawl alternative GET API', 'AI web scraper', 'RAG Markdown extraction'],
  },
  {
    slug: 'apify',
    provider: 'Apify',
    officialUrl: 'https://apify.com/',
    description: 'Compare extractor.sh with Apify for AI agents, public URL extraction, Actors, automation, and web data workflows.',
    providerStrength: 'Apify is a general automation platform built around Actors, datasets, schedules, integrations, and a large marketplace of specialized tools.',
    chooseProvider: ['You need scheduled jobs, datasets, or multi-step automation.', 'You want a marketplace of specialized scrapers.', 'You need to build and deploy custom scraping programs.'],
    chooseExtractor: ['You want a small synchronous endpoint.', 'You do not need jobs, storage, or workflow orchestration.', 'Your input is a public page URL and your output is Markdown or JSON.'],
    keywords: ['Apify alternative', 'Apify alternative for AI agents', 'simple scraping API', 'public URL to Markdown'],
  },
  {
    slug: 'scraperapi',
    provider: 'ScraperAPI',
    officialUrl: 'https://www.scraperapi.com/',
    description: 'Compare extractor.sh with ScraperAPI for proxy-backed scraping, JavaScript rendering, AI agents, and Markdown extraction.',
    providerStrength: 'ScraperAPI focuses on proxy-backed web requests and offers JavaScript rendering, geotargeting, sessions, and synchronous or asynchronous workflows.',
    chooseProvider: ['You need proxy rotation, sessions, or geotargeting.', 'You want raw target HTML for your own parser.', 'You need rendering controls for arbitrary websites.'],
    chooseExtractor: ['You want cleaned content instead of raw HTML.', 'You prefer one cacheable GET request with no API key in the preview.', 'You need consistent fields across supported sources.'],
    keywords: ['ScraperAPI alternative', 'Scraper API alternative for AI', 'URL to Markdown API', 'AI-ready web data'],
  },
  {
    slug: 'browserless',
    provider: 'Browserless',
    officialUrl: 'https://www.browserless.io/',
    description: 'Compare extractor.sh with Browserless for browser automation, rendered HTML, AI extraction, and lightweight URL processing.',
    providerStrength: 'Browserless provides managed browser infrastructure and REST endpoints for rendered HTML, screenshots, selectors, unblocking, and browser functions.',
    chooseProvider: ['You need direct browser automation or CDP access.', 'You need screenshots, scripted actions, or CSS selector extraction.', 'Rendering is the core of your workload.'],
    chooseExtractor: ['You want browser rendering to be a last resort.', 'You need Markdown or normalized JSON rather than a browser session.', 'Low-cost cache hits matter for repeated public URLs.'],
    keywords: ['Browserless alternative', 'Browserless alternative for AI', 'browser scraping alternative', 'cached extraction API'],
  },
  {
    slug: 'zyte',
    provider: 'Zyte',
    officialUrl: 'https://www.zyte.com/zyte-api/',
    description: 'Compare extractor.sh with Zyte API for automatic extraction, browser rendering, AI data workflows, and simple public URLs.',
    providerStrength: 'Zyte API offers managed HTTP and browser requests plus automatic extraction models for pages such as products, articles, jobs, and search results.',
    chooseProvider: ['You need managed proxies, geolocation, sessions, or browser actions.', 'You need specialized automatic extraction schemas.', 'You are building a larger enterprise scraping operation.'],
    chooseExtractor: ['You need a small GET-only interface.', 'You want immediately reusable Markdown for AI or RAG.', 'You value source-specific public extraction without location controls.'],
    keywords: ['Zyte alternative', 'Zyte API alternative for AI', 'automatic extraction API', 'RAG web content API'],
  },
];
