export const CURRENT_YEAR = new Date().getUTCFullYear();

export interface PlatformArticle {
  slug: string;
  platform: string;
  headline?: string;
  eyebrow?: string;
  sourcePath: string;
  sourceLinkLabel?: string;
  exampleUrl: string;
  apiExample?: string;
  quickAnswerTitle?: string;
  quickAnswer?: string;
  ctaPath?: string;
  ctaLabel?: string;
  description: string;
  introduction: string;
  extracts: string[];
  aiUseCases: string[];
  boundaries: string[];
  keywords: string[];
}

export const platformArticles: PlatformArticle[] = [
  {
    slug: 'scrape-amazon-data',
    platform: 'Amazon',
    sourcePath: '/amazon/',
    exampleUrl: 'https://www.amazon.de/echo-dot-2022/dp/B09B8X9RGM',
    description: `How to extract public Amazon product and search data for AI applications in ${CURRENT_YEAR} using one cacheable GET request.`,
    introduction: 'Amazon product and search pages contain useful facts alongside navigation, recommendations, account controls, and personalized storefront content. Focused extraction keeps the public product details or search result cards and removes most of that surrounding noise.',
    extracts: ['Product titles and canonical URLs', 'Public price, rating, availability, and image when present', 'Up to 20 normalized items from one search page', 'Product descriptions and visible specifications on exact product pages'],
    aiUseCases: ['Product research assistants', 'RAG indexes for public catalogs', 'Catalog normalization and enrichment', 'LLM-ready competitive research'],
    boundaries: ['Exact product pages and search URLs containing a query receive specialized extraction.', 'Search feeds are capped at 20 products; category browsing, pagination, carts, accounts, reviews, and personalized offers are unavailable.', 'Prices and availability can change and may be cached for up to one hour.'],
    keywords: ['Amazon scraper API', 'Amazon search API', 'Amazon product data API', 'AI product extraction', 'Amazon data for LLM', 'RAG ecommerce data'],
  },
  {
    slug: 'scrape-app-store-data',
    platform: 'App Store',
    sourcePath: '/app-store/',
    exampleUrl: 'https://apps.apple.com/us/app/chatgpt/id6448311069',
    description: `How to extract public Apple App Store app metadata for AI agents and product pipelines in ${CURRENT_YEAR}.`,
    introduction: 'App Store listings combine product facts with a large interactive storefront. A normalized software product entity keeps the public app identity, developer, description, price, rating, release details, icon, and screenshots in a predictable format.',
    extracts: ['App name, numeric ID, developer, and canonical URL', 'Integer minor-unit price and display price', 'Rating, rating count, category, version, and operating-system requirement', 'Public app icon, screenshots, description, and release notes'],
    aiUseCases: ['App research and discovery agents', 'Software catalog enrichment', 'App intelligence RAG pipelines', 'Cross-store product normalization'],
    boundaries: ['Only exact public app detail URLs are supported.', 'Search results, charts, reviews, account data, and app binaries are not included.', 'Availability and prices can vary by country and results may be cached for up to one hour.'],
    keywords: ['App Store scraper API', 'Apple app metadata API', 'App Store data for AI', 'mobile app RAG', 'AI app intelligence'],
  },
  {
    slug: 'scrape-bluesky-data',
    platform: 'Bluesky',
    sourcePath: '/bluesky/',
    exampleUrl: 'https://bsky.app/profile/bsky.app',
    description: `How to extract public Bluesky profiles and posts for AI agents and data pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Bluesky has distinct profile and post URLs. Converting both into the same response shape makes the content easier to search, summarize, and combine with other public sources.',
    extracts: ['Public profile details', 'Recent public profile posts as feed items', 'Individual public post text and authorship', 'Canonical links and timestamps when available'],
    aiUseCases: ['Public conversation monitoring', 'AI research agents', 'Semantic search over public posts', 'RAG datasets with source attribution'],
    boundaries: ['Private and deleted content is unavailable.', 'Replies and parent threads are not included.', 'Quoted or embedded content may be summarized rather than expanded completely.'],
    keywords: ['Bluesky scraper API', 'Bluesky data extraction', 'Bluesky API for AI', 'social data RAG', 'AI agent web data'],
  },
  {
    slug: 'scrape-google-news-data',
    platform: 'Google News',
    sourcePath: '/google-news/',
    exampleUrl: 'https://news.google.com/search?q=Cloudflare&hl=en-US&gl=US&ceid=US%3Aen',
    description: `How to extract public Google News searches, topics, and top stories for AI agents and RAG pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Google News groups current reporting from many publishers, but its browser interface is not a stable ingestion format. A normalized article feed keeps the public title, publisher, date, summary, and source link in a predictable shape for downstream systems.',
    extracts: ['Up to 50 public article results per page', 'Article titles, publishers, and publisher URLs when available', 'Publication timestamps and public summaries', 'Source-linked article entities in one normalized feed'],
    aiUseCases: ['Current-events research agents', 'Source discovery for RAG pipelines', 'Publisher and topic monitoring', 'News classification and enrichment'],
    boundaries: ['Search, topic, and top-stories pages are supported; personalized For You results are unavailable.', 'The result contains public metadata and summaries, not the full publisher article body.', 'Google Search and Google Shopping are separate products and are not included.'],
    keywords: ['Google News scraper API', 'Google News extraction API', 'Google News data for AI', 'news RAG pipeline', 'AI news extraction'],
  },
  {
    slug: 'scrape-google-play-data',
    platform: 'Google Play',
    sourcePath: '/google-play/',
    exampleUrl: 'https://play.google.com/store/apps/details?id=com.openai.chatgpt',
    description: `How to extract public Google Play app metadata for AI agents and product pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Google Play app pages expose useful public product metadata alongside an interactive storefront. Normalization turns an ordinary app URL into one consistent software product with developer, price, rating, description, icon, and screenshots.',
    extracts: ['App name, package ID, developer, and canonical URL', 'Integer minor-unit price and display price', 'Rating, rating count, category, operating system, and content rating', 'Public app icon, screenshots, and full listing description'],
    aiUseCases: ['Android app discovery agents', 'Software catalog enrichment', 'App market RAG pipelines', 'Cross-store product comparison'],
    boundaries: ['Only exact public app detail URLs are supported.', 'Search results, categories, reviews, account data, and APK downloads are not included.', 'Availability and prices can vary by country and results may be cached for up to one hour.'],
    keywords: ['Google Play scraper API', 'Google Play app metadata API', 'Google Play data for AI', 'Android app RAG', 'AI app intelligence'],
  },
  {
    slug: 'scrape-instagram-data',
    platform: 'Instagram',
    sourcePath: '/instagram/',
    exampleUrl: 'https://www.instagram.com/instagram/',
    description: `How to extract public Instagram posts, reels, and profiles for AI workflows in ${CURRENT_YEAR}.`,
    introduction: 'Public Instagram pages are visually rich, but AI systems usually need compact text, authorship, dates, and links. Normalization turns supported public posts and profiles into predictable Markdown or JSON without returning active embeds.',
    extracts: ['Public post and reel captions when exposed', 'Public account names and handles', 'Recent public profile posts', 'Media type, timestamps, and canonical links when available'],
    aiUseCases: ['Brand and creator research', 'AI-assisted content analysis', 'Public social knowledge bases', 'Cross-platform RAG ingestion'],
    boundaries: ['Private, deleted, login-only, and age-gated content is unavailable.', 'Stories, comments, transcripts, and media downloads are not included.', 'The public source can sometimes expose only minimal post metadata.'],
    keywords: ['Instagram scraper API', 'Instagram data for AI', 'Instagram post extraction', 'Instagram RAG pipeline', 'AI social media data'],
  },
  {
    slug: 'scrape-mastodon-data',
    platform: 'Mastodon',
    sourcePath: '/mastodon/',
    exampleUrl: 'https://mastodon.social/@trwnh/99664077509711321',
    description: `How to extract public Mastodon posts from federated instances for AI and RAG workflows in ${CURRENT_YEAR}.`,
    introduction: 'Mastodon is distributed across many independently operated instances, but compatible public status pages share a common structure. Normalization gives AI systems one predictable document shape without requiring instance-specific client code.',
    extracts: ['Public status text and canonical link', 'Display name and federated account handle', 'Publication timestamp and content warning', 'Media descriptions supplied by the author'],
    aiUseCases: ['Federated social research', 'Public-interest monitoring', 'Source-linked RAG collections', 'Cross-network AI analysis'],
    boundaries: ['Private, followers-only, deleted, and unavailable statuses are not accessible.', 'Timelines, complete threads, replies, and media downloads are not included.', 'Instances must expose compatible public endpoints.'],
    keywords: ['Mastodon scraper API', 'Fediverse data extraction', 'Mastodon data for AI', 'Mastodon RAG pipeline', 'federated social data'],
  },
  {
    slug: 'scrape-reddit-data',
    platform: 'Reddit',
    sourcePath: '/reddit/',
    exampleUrl: 'https://www.reddit.com/r/CloudFlare/',
    description: `How to extract public Reddit posts, communities, and profiles for AI and RAG pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Reddit pages mix post content with voting controls, navigation, recommendations, and long comment trees. A normalized extraction is useful when the goal is the public post or a compact community feed rather than a complete discussion archive.',
    extracts: ['Public post titles and bodies', 'Public subreddit and community feeds', 'Public user profile feeds', 'Authors, timestamps, and canonical URLs when available'],
    aiUseCases: ['Topic and community research', 'AI trend analysis', 'Public feedback summarization', 'Source-linked RAG collections'],
    boundaries: ['Private and quarantined communities are unsupported.', 'Complete comment trees are not included.', 'Deleted or restricted posts cannot be recovered.'],
    keywords: ['Reddit scraper API', 'Reddit data extraction', 'Reddit API for AI', 'Reddit RAG data', 'AI community research'],
  },
  {
    slug: 'scrape-shopify-data',
    platform: 'Shopify',
    sourcePath: '/shopify/',
    exampleUrl: 'https://www.allbirds.com/products/mens-cruiser-shadow-blue-natural-white-sole',
    description: `How to extract public Shopify product and catalog data for AI applications in ${CURRENT_YEAR}.`,
    introduction: 'Shopify storefront themes vary widely even though their public products share common concepts. Returning a consistent product entity or catalog feed removes theme-specific presentation from downstream AI and data work.',
    extracts: ['Public product titles and descriptions', 'Variants, prices, and product links when available', 'Public collection and storefront catalogs', 'Up to 50 normalized catalog items per feed'],
    aiUseCases: ['Commerce assistants and product search', 'Catalog RAG systems', 'Public market and assortment research', 'Cross-store product normalization'],
    boundaries: ['Stores can disable or protect public product data.', 'Checkout, customer, order, and administrative data is unavailable.', 'Catalog feeds are capped at 50 products.'],
    keywords: ['Shopify scraper API', 'Shopify products JSON API', 'Shopify data for AI', 'ecommerce RAG', 'AI catalog extraction'],
  },
  {
    slug: 'scrape-soundcloud-data',
    platform: 'SoundCloud',
    sourcePath: '/soundcloud/',
    exampleUrl: 'https://soundcloud.com/forss/flickermood',
    description: `How to extract public SoundCloud track, playlist, and creator metadata for AI workflows in ${CURRENT_YEAR}.`,
    introduction: 'SoundCloud pages center an interactive audio player, while many AI workflows only need the public title, creator, description, artwork, type, and source URL. A compact audio or profile entity is easier to index and attribute.',
    extracts: ['Public track, playlist, set, or profile title', 'Creator identity and public description', 'Artwork and content type when available', 'Canonical source link'],
    aiUseCases: ['Audio discovery assistants', 'Music and creator research', 'Metadata-based recommendation pipelines', 'Source catalogs for multimodal RAG'],
    boundaries: ['Private and deleted audio is unavailable.', 'Comments, waveforms, transcripts, and media downloads are not included.', 'The extractor does not analyze the recording itself.'],
    keywords: ['SoundCloud scraper API', 'SoundCloud metadata extraction', 'SoundCloud data for AI', 'audio RAG pipeline', 'AI music research'],
  },
  {
    slug: 'scrape-spotify-data',
    platform: 'Spotify',
    sourcePath: '/spotify/',
    exampleUrl: 'https://open.spotify.com/episode/7makk4oTQel546B0PZlDM5',
    description: `How to extract public Spotify music and podcast metadata for AI and RAG applications in ${CURRENT_YEAR}.`,
    introduction: 'Spotify links can represent tracks, albums, artists, playlists, podcast shows, or episodes. Converting supported public links into a consistent document makes them easier to classify and connect with other knowledge sources.',
    extracts: ['Public title and content type', 'Artwork and source URL when available', 'Tracks, albums, artists, playlists, shows, and episodes', 'One normalized Markdown or JSON document'],
    aiUseCases: ['Music and podcast discovery agents', 'Media knowledge graphs', 'Public metadata enrichment', 'Multimodal RAG source catalogs'],
    boundaries: ['Private and unavailable content is not accessible.', 'Lyrics, transcripts, playback data, audio analysis, and media downloads are not included.', 'Metadata completeness depends on the public fields Spotify exposes.'],
    keywords: ['Spotify scraper API', 'Spotify metadata extraction', 'Spotify data for AI', 'podcast RAG pipeline', 'AI music data'],
  },
  {
    slug: 'scrape-tiktok-data',
    platform: 'TikTok',
    sourcePath: '/tiktok/',
    exampleUrl: 'https://www.tiktok.com/@scout2015/video/6718335390845095173',
    description: `How to extract public TikTok posts and profiles for AI agents and RAG workflows in ${CURRENT_YEAR}.`,
    introduction: 'TikTok is video-first, but its public pages can still provide useful textual context such as captions, creator identity, dates, hashtags, and sound attribution. That metadata is often enough for discovery and AI classification without downloading media.',
    extracts: ['Public video and photo-post captions', 'Creator names and handles', 'Dates, hashtags, duration, and sound details when available', 'Public creator profile details'],
    aiUseCases: ['AI content discovery', 'Public trend classification', 'Creator research workflows', 'Cross-platform social RAG'],
    boundaries: ['Private, deleted, login-only, and age-restricted content is unavailable.', 'Comments, transcripts, and media downloads are not included.', 'Profile extraction does not provide a complete posting history.'],
    keywords: ['TikTok scraper API', 'TikTok data extraction 2026', 'TikTok data for AI', 'TikTok RAG pipeline', 'AI trend data'],
  },
  {
    slug: 'scrape-vimeo-data',
    platform: 'Vimeo',
    sourcePath: '/vimeo/',
    exampleUrl: 'https://vimeo.com/286898202',
    description: `How to extract public Vimeo video metadata for AI agents and data pipelines in ${CURRENT_YEAR}.`,
    introduction: 'A Vimeo video page combines playback with creator and presentation controls. For search, cataloging, and AI ingestion, the public title, author, description, date, duration, thumbnail, and source URL are usually the useful layer.',
    extracts: ['Public video title and description', 'Author and upload date when available', 'Duration and thumbnail', 'Canonical Vimeo source link'],
    aiUseCases: ['Video discovery agents', 'Public media catalogs', 'Metadata classification and enrichment', 'Multimodal RAG source indexes'],
    boundaries: ['Private and embed-disabled videos are unavailable.', 'Transcripts, captions, comments, and media downloads are not included.', 'The result describes the video rather than analyzing its audiovisual content.'],
    keywords: ['Vimeo scraper API', 'Vimeo metadata extraction', 'Vimeo data for AI', 'video RAG pipeline', 'AI video catalog'],
  },
  {
    slug: 'scrape-x-data',
    platform: 'X',
    sourcePath: '/x/',
    exampleUrl: 'https://x.com/jack/status/20',
    description: `How to extract public X posts as clean data for AI applications and agents in ${CURRENT_YEAR}.`,
    introduction: 'A public X status URL can be useful evidence for an AI workflow, but the surrounding interface is not. A post entity keeps the text, author, date when available, and original link in a reusable representation.',
    extracts: ['Public post text', 'Public author information', 'Canonical status links', 'Publication timestamps when available'],
    aiUseCases: ['AI research with source links', 'Public announcement monitoring', 'Knowledge-base ingestion', 'Cross-platform content normalization'],
    boundaries: ['Only individual public status URLs are supported.', 'Private, deleted, and age-gated posts are unavailable.', 'Timelines, search results, replies, and complete threads are not included.'],
    keywords: ['X scraper API', 'Twitter scraper API', 'X data for AI', 'tweet extraction API', 'social RAG pipeline'],
  },
  {
    slug: 'scrape-youtube-data',
    platform: 'YouTube',
    sourcePath: '/youtube/',
    exampleUrl: 'https://www.youtube.com/@Cloudflare',
    description: `How to extract public YouTube metadata, channels, and playlists for AI pipelines in ${CURRENT_YEAR}.`,
    introduction: 'YouTube pages provide valuable public metadata even when a workflow does not need the media itself. Normalized video and channel results make titles, descriptions, authors, dates, and links easier to index and combine with other sources.',
    extracts: ['Public video titles and descriptions', 'Channel and playlist feeds', 'Author, publication date, and canonical URL', 'Normalized Markdown or JSON metadata'],
    aiUseCases: ['Video discovery agents', 'AI research indexes', 'Metadata-based topic classification', 'Source catalogs for multimodal pipelines'],
    boundaries: ['Private, removed, member-only, and age-gated content is unavailable.', 'Transcripts, captions, spoken content, and media downloads are not included.', 'Results describe public videos; they do not analyze the audiovisual content.'],
    keywords: ['YouTube scraper API', 'YouTube metadata API', 'YouTube data for AI', 'video RAG pipeline', 'AI video research'],
  },
  {
    slug: 'scrape-woocommerce-data',
    platform: 'WooCommerce',
    sourcePath: '/woocommerce/',
    exampleUrl: 'https://muista.eu/shop/rugs/sunrise-rug/',
    description: `How to extract public WooCommerce product, variant, and catalog data for AI applications in ${CURRENT_YEAR}.`,
    introduction: 'WooCommerce stores can look completely different while describing the same product concepts. Normalized product entities and catalog feeds remove theme-specific presentation from product discovery, comparison, and AI ingestion.',
    extracts: ['Public product titles, descriptions, images, and canonical URLs', 'Integer minor-unit prices and display prices', 'Variants, stock state, categories, and attributes when available', 'Up to 50 normalized products from supported shop, search, and category pages'],
    aiUseCases: ['Commerce assistants and product search', 'Catalog enrichment and normalization', 'Competitive assortment research', 'Product-data RAG pipelines'],
    boundaries: ['Only public storefront data is available.', 'Customer, cart, checkout, order, and administrative data is never included.', 'Catalog feeds are capped at 50 products and stores can restrict public product data.'],
    keywords: ['WooCommerce scraper API', 'WooCommerce product data API', 'WooCommerce data for AI', 'ecommerce RAG', 'AI catalog extraction'],
  },
  {
    slug: 'scrape-yahoo-finance-data',
    platform: 'Yahoo Finance',
    sourcePath: '/yahoo-finance/',
    exampleUrl: 'https://finance.yahoo.com/quote/AAPL/',
    description: `How to search stock symbols and retrieve public market snapshots with configurable currency and history for AI workflows in ${CURRENT_YEAR}.`,
    introduction: 'Market pages mix quote data, charts, navigation, analysis, and news. The finance API can first resolve a company name into equity symbols, then keep the latest public snapshot and a bounded, configurable history compact enough for research assistants and data pipelines. A requested quote currency converts the snapshot and chart-ready history in the same operation; ordinary Yahoo Finance URLs still use the generic extractor with a one-month native-currency default.',
    extracts: ['Company-name and partial-ticker equity search', 'Latest available public market snapshot in the native or requested quote currency', 'Configurable history from one day through the maximum available range, capped at 512 points', 'Exchange, symbol, market state, conversion metadata, and canonical URL when available', 'A source-linked Markdown or schema-v1 JSON document'],
    aiUseCases: ['Market research assistants', 'Source-linked financial RAG', 'Public quote monitoring', 'Company and security research'],
    boundaries: ['Values may be delayed and are not suitable for order execution.', 'Only recognized public quote and price-history pages are supported.', 'The output is public market information, not financial or investment advice.'],
    keywords: ['Yahoo Finance scraper API', 'stock price data API for AI', 'Yahoo Finance data extraction', 'financial RAG data', 'AI market research'],
  },
  {
    slug: 'web-search-api-for-ai-agents',
    platform: 'Web Search API',
    headline: `Web Search API for AI Agents in ${CURRENT_YEAR}`,
    eyebrow: `Web search guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/search/',
    sourceLinkLabel: 'Read the web search API docs',
    exampleUrl: 'https://extractor.sh/docs/search/',
    apiExample: `curl --get 'https://extractor.sh/api/search' \\
  --data-urlencode 'q=best web extraction APIs for AI agents' \\
  --data-urlencode 'limit=5' \\
  --data-urlencode 'format=json'`,
    quickAnswerTitle: 'Give an agent focused, source-linked search results.',
    quickAnswer: 'Send a query to the web search endpoint and receive up to 10 ordered results as Markdown or provider-neutral schema-v1 JSON. Each result retains its source URL so agents can inspect evidence instead of relying on an uncited answer.',
    ctaPath: '/docs/search/',
    ctaLabel: 'Start with web search',
    description: `Use a simple web search API to give AI agents ordered, source-linked Markdown or JSON results in ${CURRENT_YEAR}.`,
    introduction: 'AI agents often need current sources before they can answer confidently. A focused search endpoint returns compact result documents without making your application depend on a search provider’s private response format.',
    extracts: ['Up to 10 ordered web results', 'Titles, URLs, snippets, and source metadata', 'Markdown for model context or provider-neutral schema-v1 JSON', 'A cacheable response for repeated identical searches'],
    aiUseCases: ['Agent research and tool use', 'Source discovery before RAG ingestion', 'Current-information grounding', 'Search-enhanced generation'],
    boundaries: ['The endpoint returns public search results, not personalized browsing history.', 'A request returns at most 10 results.', 'Search results still need source evaluation before high-stakes use.'],
    keywords: ['web search API for AI agents', 'LLM web search API', 'RAG search API', 'AI search tool', 'source linked web search'],
  },
  {
    slug: 'news-search-api-for-ai-agents',
    platform: 'News Search API',
    headline: `News Search API for AI Agents in ${CURRENT_YEAR}`,
    eyebrow: `News search guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/news/',
    sourceLinkLabel: 'Read the news search API docs',
    exampleUrl: 'https://extractor.sh/docs/news/',
    apiExample: `curl --get 'https://extractor.sh/api/news' \\
  --data-urlencode 'q=artificial intelligence' \\
  --data-urlencode 'limit=10' \\
  --data-urlencode 'format=json'`,
    quickAnswerTitle: 'Retrieve current article leads with source attribution.',
    quickAnswer: 'Send a topic to the news endpoint and receive up to 50 ordered public article results. Use JSON for structured pipelines or Markdown when an AI agent should read the feed directly.',
    ctaPath: '/docs/news/',
    ctaLabel: 'Start with news search',
    description: `Find current, source-linked public news for AI agents, monitoring, and RAG pipelines with one GET API in ${CURRENT_YEAR}.`,
    introduction: 'News research is most useful when every result includes a publisher, date, summary, and source link. A normalized news feed gives agents those fields without coupling the application to one provider-specific response.',
    extracts: ['Up to 50 public article results', 'Titles, publishers, dates, summaries, and source links', 'Markdown or provider-neutral schema-v1 JSON', 'Ordered results for a submitted query'],
    aiUseCases: ['Current-events research agents', 'News monitoring and classification', 'Source discovery for RAG', 'Publisher and topic analysis'],
    boundaries: ['Results contain public article metadata and summaries rather than guaranteed full article text.', 'Coverage and freshness depend on publicly available news results.', 'Sources should be verified before high-stakes decisions.'],
    keywords: ['news search API for AI', 'AI news API', 'RAG news search', 'news search API for agents', 'current events API'],
  },
  {
    slug: 'image-search-api-for-ai-agents',
    platform: 'Image Search API',
    headline: `Image Search API for AI Agents in ${CURRENT_YEAR}`,
    eyebrow: `Image search guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/images/',
    sourceLinkLabel: 'Read the image search API docs',
    exampleUrl: 'https://extractor.sh/docs/images/',
    apiExample: `curl --get 'https://extractor.sh/api/images' \\
  --data-urlencode 'q=solar panels' \\
  --data-urlencode 'limit=10' \\
  --data-urlencode 'format=json'`,
    quickAnswerTitle: 'Search reusable images without losing attribution.',
    quickAnswer: 'Submit an image query and receive up to 20 public image documents with creator and license metadata when available. The normalized response helps applications preserve attribution while selecting visual sources.',
    ctaPath: '/docs/images/',
    ctaLabel: 'Start with image search',
    description: `Search public images with creator and license metadata for AI agents and media workflows in ${CURRENT_YEAR}.`,
    introduction: 'An image URL alone is rarely enough for responsible reuse. A useful image-search response also carries the source, creator, license, dimensions, and preview metadata that downstream applications need.',
    extracts: ['Up to 20 ordered public image documents', 'Source and image URLs', 'Creator and license metadata when available', 'Dimensions, previews, and descriptive fields when exposed'],
    aiUseCases: ['Visual research assistants', 'Licensed asset discovery', 'Multimodal RAG source collection', 'Editorial and presentation workflows'],
    boundaries: ['License metadata must still be reviewed before reuse.', 'The endpoint searches public catalogs rather than private media libraries.', 'Availability and metadata completeness vary by source.'],
    keywords: ['image search API for AI', 'licensed image search API', 'AI image search tool', 'multimodal RAG images', 'image API with attribution'],
  },
  {
    slug: 'place-search-api-for-ai-agents',
    platform: 'Place Search API',
    headline: `Place Search API for AI Agents in ${CURRENT_YEAR}`,
    eyebrow: `Place search guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/places/',
    sourceLinkLabel: 'Read the place search API docs',
    exampleUrl: 'https://extractor.sh/docs/places/',
    apiExample: `curl --get 'https://extractor.sh/api/places' \\
  --data-urlencode 'q=Brandenburg Gate Berlin' \\
  --data-urlencode 'limit=5' \\
  --data-urlencode 'format=json'`,
    quickAnswerTitle: 'Turn one place query into structured candidates.',
    quickAnswer: 'Submit a place query and receive up to 10 provider-neutral place documents with coordinates and address fields when available. Results retain required OpenStreetMap attribution.',
    ctaPath: '/docs/places/',
    ctaLabel: 'Start with place search',
    description: `Add provider-neutral place search with coordinates and address data to AI agents in ${CURRENT_YEAR}.`,
    introduction: 'Location-aware agents need structured candidates rather than an autocomplete widget. A submitted place query can return names, coordinates, address components, and source attribution in one predictable response.',
    extracts: ['Up to 10 ordered place candidates', 'Names, coordinates, and address components when available', 'Provider-neutral schema-v1 JSON or Markdown', 'OpenStreetMap attribution'],
    aiUseCases: ['Travel and local discovery agents', 'Place normalization and geocoding', 'Location-aware RAG', 'Research and itinerary workflows'],
    boundaries: ['The public service is intended for fair-use submitted searches, not autocomplete traffic.', 'Results are candidates and should be validated for critical navigation.', 'Coverage and address detail vary by location.'],
    keywords: ['place search API for AI', 'geocoding API for agents', 'location search API', 'AI travel agent API', 'OpenStreetMap place search'],
  },
  {
    slug: 'url-to-markdown-api',
    platform: 'URL to Markdown API',
    headline: `URL to Markdown API for LLMs and RAG in ${CURRENT_YEAR}`,
    eyebrow: `Markdown extraction guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/quickstart/',
    sourceLinkLabel: 'Read the extraction quickstart',
    exampleUrl: 'https://example.com/',
    quickAnswerTitle: 'Convert a public URL into model-ready Markdown.',
    quickAnswer: 'Pass a public URL to the extraction endpoint with format=markdown. The response removes interface noise, preserves useful hierarchy, and keeps the source URL available for attribution.',
    description: `Convert public webpages into clean, source-linked Markdown for LLM prompts and RAG pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Raw HTML spends tokens on scripts, navigation, styling, and interface labels. Clean Markdown keeps headings, paragraphs, lists, and links in a compact representation that models and chunking pipelines can use directly.',
    extracts: ['Readable headings, paragraphs, lists, and links', 'Canonical URL and public page metadata', 'Platform-aware entities for supported sources', 'A plain Markdown response for direct model input'],
    aiUseCases: ['RAG document ingestion', 'Agent reading tools', 'Source-grounded summarization', 'LLM prompt context'],
    boundaries: ['Only publicly reachable GET URLs are accepted.', 'Login walls, paywalls, CAPTCHAs, and access controls are not bypassed.', 'Media transcripts, crawling, and authenticated content are outside the endpoint.'],
    keywords: ['URL to Markdown API', 'webpage to Markdown API', 'Markdown scraper for LLM', 'RAG extraction API', 'AI web reader'],
  },
  {
    slug: 'webpage-to-json-api',
    platform: 'Webpage to JSON API',
    headline: `Webpage to JSON API with Semantic Entities in ${CURRENT_YEAR}`,
    eyebrow: `Structured extraction guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/schema/',
    sourceLinkLabel: 'Explore the schema-v1 reference',
    exampleUrl: 'https://example.com/',
    quickAnswerTitle: 'Normalize public pages into one stable JSON schema.',
    quickAnswer: 'Request format=json to receive schema-v1 output with a semantic entity type, source URL, shared metadata, and type-specific fields. The same contract covers ordinary documents and supported articles, products, posts, profiles, media, and feeds.',
    ctaPath: '/docs/schema/',
    ctaLabel: 'Explore the JSON schema',
    description: `Turn public webpages into normalized schema-v1 JSON for AI agents and application pipelines in ${CURRENT_YEAR}.`,
    introduction: 'Every site structures data differently. A semantic JSON contract lets an application handle products, posts, profiles, videos, articles, feeds, and ordinary documents without maintaining a parser for every visual layout.',
    extracts: ['Schema version and semantic entity type', 'Source URL, title, description, author, dates, and media when available', 'Type-specific product, post, profile, audio, video, and feed fields', 'Integer minor-unit prices for products and variants'],
    aiUseCases: ['Typed agent tools', 'Knowledge-graph ingestion', 'Cross-source normalization', 'Structured RAG metadata'],
    boundaries: ['Unavailable optional data is not invented.', 'Only public page content is represented.', 'Applications should validate source freshness and retain canonical URLs.'],
    keywords: ['webpage to JSON API', 'structured web extraction API', 'semantic JSON scraper', 'AI data extraction schema', 'RAG metadata API'],
  },
  {
    slug: 'web-data-api-for-ai-agents',
    platform: 'Web Data API',
    headline: `One Web Data API for AI Agents in ${CURRENT_YEAR}`,
    eyebrow: `Agent data guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/api/',
    sourceLinkLabel: 'Explore all API endpoints',
    exampleUrl: 'https://extractor.sh/docs/api/',
    apiExample: `curl --get 'https://extractor.sh/api/extract' \\
  --data-urlencode 'url=https://example.com/' \\
  --data-urlencode 'format=json'`,
    quickAnswerTitle: 'Use one API for extraction and focused search.',
    quickAnswer: 'Give an AI agent a small set of GET tools for public URL extraction plus web, news, image, and place search. All endpoints can return Markdown or schema-v1 JSON and share the same account, limits, and credit model.',
    ctaPath: '/docs/api/',
    ctaLabel: 'Explore the API',
    description: `Combine public URL extraction with web, news, image, and place search for AI agents through one API in ${CURRENT_YEAR}.`,
    introduction: 'Agents often need both retrieval modes: open a known source and discover sources for an unanswered query. A compact API surface keeps these operations consistent without turning the integration into a crawling or browser-automation project.',
    extracts: ['Public webpage extraction', 'Web and news search results', 'Image results with attribution metadata', 'Place results with coordinates and address fields'],
    aiUseCases: ['General research agents', 'RAG source discovery and ingestion', 'Multimodal research tools', 'Tool-using assistants'],
    boundaries: ['The service does not crawl entire sites or execute arbitrary browser workflows.', 'All requests must target public information.', 'Endpoint-specific result limits and attribution requirements still apply.'],
    keywords: ['web data API for AI agents', 'AI agent tools API', 'search and extraction API', 'RAG data API', 'LLM web tools'],
  },
  {
    slug: 'mcp-web-search-server',
    platform: 'Web Search MCP Server',
    headline: `Hosted MCP Server for Web Search and Extraction in ${CURRENT_YEAR}`,
    eyebrow: `MCP integration guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/mcp/',
    sourceLinkLabel: 'Read the MCP server guide',
    exampleUrl: 'https://extractor.sh/docs/mcp/',
    apiExample: `{
  "mcpServers": {
    "extractor": { "url": "https://extractor.sh/mcp" }
  }
}`,
    quickAnswerTitle: 'Connect agents to one hosted MCP endpoint.',
    quickAnswer: 'Configure the hosted MCP URL to expose public-page extraction plus web, news, image, and place search as agent tools. The server is stateless and follows the same cache, allowance, and credit behavior as the public API.',
    ctaPath: '/docs/mcp/',
    ctaLabel: 'Connect the MCP server',
    description: `Connect AI agents to hosted web extraction, search, news, image, and place tools through MCP in ${CURRENT_YEAR}.`,
    introduction: 'MCP clients can discover and call web-data tools without a custom SDK. A hosted server is useful when an agent needs both known-URL extraction and focused discovery while retaining source-linked results.',
    extracts: ['Public URL extraction tools', 'Web and news search tools', 'Image and place search tools', 'Markdown or normalized structured results'],
    aiUseCases: ['Coding and research agents', 'Desktop AI assistants', 'MCP-enabled RAG workflows', 'Source-grounded tool use'],
    boundaries: ['The server is stateless and does not keep request history.', 'It cannot access private pages or bypass access controls.', 'The MCP tools use the same public limits and account credits as the API.'],
    keywords: ['MCP web search server', 'MCP scraping server', 'MCP tools for AI agents', 'hosted MCP extraction', 'RAG MCP server'],
  },
  {
    slug: 'ecommerce-product-data-api',
    platform: 'Ecommerce Product Data API',
    headline: `Ecommerce Product Data API for AI in ${CURRENT_YEAR}`,
    eyebrow: `Commerce data guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/sources/',
    sourceLinkLabel: 'See all supported sources',
    exampleUrl: 'https://www.amazon.de/echo-dot-2022/dp/B09B8X9RGM',
    quickAnswerTitle: 'Normalize public product pages across storefronts.',
    quickAnswer: 'Send a supported Amazon, Shopify, WooCommerce, App Store, or Google Play URL and receive a semantic product entity or catalog feed. Prices use integer minor units so downstream systems can compare values without floating-point errors.',
    description: `Extract normalized public Amazon, Shopify, WooCommerce, App Store, and Google Play product data for AI in ${CURRENT_YEAR}.`,
    introduction: 'Commerce pages use different names and layouts for the same concepts: title, description, price, variants, availability, images, and category. One semantic response makes cross-store research and product-aware agents considerably easier to build.',
    extracts: ['Public product titles, descriptions, URLs, and images', 'Integer minor-unit prices with separate display text', 'Variants, availability, ratings, and attributes when exposed', 'Catalog or search feeds for supported storefront pages'],
    aiUseCases: ['Shopping and product research agents', 'Cross-store catalog normalization', 'Competitive assortment analysis', 'Commerce RAG pipelines'],
    boundaries: ['Only public catalog data is included.', 'Checkout, customer, seller, order, and administrative data is unavailable.', 'Availability and price can change after a response is cached.'],
    keywords: ['ecommerce product data API', 'product scraper API for AI', 'Amazon Shopify WooCommerce API', 'catalog data for RAG', 'AI shopping data'],
  },
  {
    slug: 'social-media-data-api-for-ai',
    platform: 'Social Media Data API',
    headline: `Public Social Media Data API for AI Agents in ${CURRENT_YEAR}`,
    eyebrow: `Social data guide / ${CURRENT_YEAR}`,
    sourcePath: '/docs/sources/',
    sourceLinkLabel: 'See all supported platforms',
    exampleUrl: 'https://bsky.app/profile/bsky.app',
    quickAnswerTitle: 'Use one schema across supported public social sources.',
    quickAnswer: 'Submit a supported public Bluesky, Instagram, Mastodon, Reddit, TikTok, X, or YouTube URL. The extractor returns a semantic post, profile, video, or feed instead of exposing each site’s interface structure.',
    description: `Normalize supported public social posts, profiles, videos, and feeds for AI agents and RAG in ${CURRENT_YEAR}.`,
    introduction: 'Public social sources describe authors, posts, profiles, media, and feeds in incompatible ways. Normalization gives research agents a predictable, source-linked record while keeping platform-specific retrieval details out of the application.',
    extracts: ['Public post text and captions when available', 'Profile names, handles, descriptions, and recent public items on supported pages', 'Authors, timestamps, canonical URLs, and media metadata', 'Semantic post, profile, video, or feed entities'],
    aiUseCases: ['Cross-platform public research', 'Brand and creator discovery', 'Source-linked social RAG', 'Public trend classification'],
    boundaries: ['Private, deleted, login-only, and restricted content is unavailable.', 'Comments, transcripts, and full account histories are not included.', 'Metadata completeness depends on what each public source exposes.'],
    keywords: ['social media data API for AI', 'social scraper API', 'public social data for RAG', 'AI agent social media tool', 'cross platform social API'],
  },
];

export interface AlternativePage {
  slug: string;
  provider: string;
  description: string;
  providerStrength: string;
  chooseProvider: string[];
  chooseExtractor: string[];
  keywords: string[];
}

export const alternativePages: AlternativePage[] = [
  {
    slug: 'scrapingbee',
    provider: 'ScrapingBee',
    description: 'Compare extractor.sh with ScrapingBee for public URL extraction, Markdown, JSON, AI agents, and RAG ingestion.',
    providerStrength: 'ScrapingBee is a broad scraping API with JavaScript rendering, proxy options, screenshots, selectors, and AI extraction controls.',
    chooseProvider: ['You need proxy selection or geotargeting.', 'You need browser interactions, screenshots, or selector-level controls.', 'You need a broad scraping infrastructure product.'],
    chooseExtractor: ['You want one cacheable GET URL.', 'You primarily need clean Markdown or normalized JSON.', 'You are feeding public pages into AI agents, search, or RAG.'],
    keywords: ['ScrapingBee alternative', 'ScrapingBee alternative for AI', 'Markdown scraping API', 'RAG web extraction API'],
  },
  {
    slug: 'firecrawl',
    provider: 'Firecrawl',
    description: 'Compare extractor.sh with Firecrawl for single-page extraction, AI-ready Markdown, crawling, and RAG workflows.',
    providerStrength: 'Firecrawl combines single-page scraping with crawling, mapping, screenshots, structured extraction, and other website-scale workflows.',
    chooseProvider: ['You need to crawl or map an entire website.', 'You need screenshots, actions, change tracking, or schema-driven extraction.', 'You want a broader ingestion platform.'],
    chooseExtractor: ['You need one public URL at a time.', 'A GET-only cache key fits your architecture.', 'You want normalized handling for supported social and commerce pages.'],
    keywords: ['Firecrawl alternative', 'Firecrawl alternative GET API', 'AI web scraper', 'RAG Markdown extraction'],
  },
  {
    slug: 'apify',
    provider: 'Apify',
    description: 'Compare extractor.sh with Apify for AI agents, public URL extraction, Actors, automation, and web data workflows.',
    providerStrength: 'Apify is a general automation platform built around Actors, datasets, schedules, integrations, and a large marketplace of specialized tools.',
    chooseProvider: ['You need scheduled jobs, datasets, or multi-step automation.', 'You want a marketplace of specialized scrapers.', 'You need to build and deploy custom scraping programs.'],
    chooseExtractor: ['You want a small synchronous endpoint.', 'You do not need jobs, storage, or workflow orchestration.', 'Your input is a public page URL and your output is Markdown or JSON.'],
    keywords: ['Apify alternative', 'Apify alternative for AI agents', 'simple scraping API', 'public URL to Markdown'],
  },
  {
    slug: 'scraperapi',
    provider: 'ScraperAPI',
    description: 'Compare extractor.sh with ScraperAPI for proxy-backed scraping, JavaScript rendering, AI agents, and Markdown extraction.',
    providerStrength: 'ScraperAPI focuses on proxy-backed web requests and offers JavaScript rendering, geotargeting, sessions, and synchronous or asynchronous workflows.',
    chooseProvider: ['You need proxy rotation, sessions, or geotargeting.', 'You want raw target HTML for your own parser.', 'You need rendering controls for arbitrary websites.'],
    chooseExtractor: ['You want cleaned content instead of raw HTML.', 'You prefer one cacheable GET request with no API key in the preview.', 'You need consistent fields across supported sources.'],
    keywords: ['ScraperAPI alternative', 'Scraper API alternative for AI', 'URL to Markdown API', 'AI-ready web data'],
  },
  {
    slug: 'browserless',
    provider: 'Browserless',
    description: 'Compare extractor.sh with Browserless for browser automation, rendered HTML, AI extraction, and lightweight URL processing.',
    providerStrength: 'Browserless provides managed browser infrastructure and REST endpoints for rendered HTML, screenshots, selectors, unblocking, and browser functions.',
    chooseProvider: ['You need direct browser automation or CDP access.', 'You need screenshots, scripted actions, or CSS selector extraction.', 'Rendering is the core of your workload.'],
    chooseExtractor: ['You want one public URL transformed into usable content.', 'You need Markdown or normalized JSON rather than a browser session.', 'Low-cost cache hits matter for repeated public URLs.'],
    keywords: ['Browserless alternative', 'Browserless alternative for AI', 'browser scraping alternative', 'cached extraction API'],
  },
  {
    slug: 'zyte',
    provider: 'Zyte',
    description: 'Compare extractor.sh with Zyte API for automatic extraction, AI data workflows, and simple public URL processing.',
    providerStrength: 'Zyte API offers managed HTTP and browser requests plus automatic extraction models for pages such as products, articles, jobs, and search results.',
    chooseProvider: ['You need managed proxies, geolocation, sessions, or browser actions.', 'You need specialized automatic extraction schemas.', 'You are building a larger enterprise scraping operation.'],
    chooseExtractor: ['You need a small GET-only interface.', 'You want immediately reusable Markdown for AI or RAG.', 'You value source-specific public extraction without location controls.'],
    keywords: ['Zyte alternative', 'Zyte API alternative for AI', 'automatic extraction API', 'RAG web content API'],
  },
  {
    slug: 'context-dev',
    provider: 'Context.dev',
    description: 'Compare extractor.sh with Context.dev for web extraction, search, structured data, brand intelligence, AI agents, and RAG workflows.',
    providerStrength: 'Context.dev is a broad web-data platform with page scraping, crawling, screenshots, structured extraction, web search, and specialized company, brand, product, and style-guide data.',
    chooseProvider: ['You need to crawl or map complete websites.', 'You need screenshots or prompt-defined structured extraction.', 'You need specialized brand, company, logo, product, or style-guide enrichment.'],
    chooseExtractor: ['You want focused public-page extraction plus web, news, image, and place search.', 'You want semantic entities for supported social, commerce, app, news, finance, and media sources.', 'You prefer a small GET API and hosted MCP server with free cache hits.'],
    keywords: ['Context.dev alternative', 'Context API alternative', 'web data API for AI', 'AI search and extraction API', 'RAG web data'],
  },
  {
    slug: 'tavily',
    provider: 'Tavily',
    description: 'Compare extractor.sh with Tavily for AI web search, URL extraction, site crawling, mapping, research, and MCP tools.',
    providerStrength: 'Tavily provides web search, URL extraction, site crawling and mapping, a research workflow, and integrations designed for AI applications and agents.',
    chooseProvider: ['You want an answer-oriented research workflow.', 'You need site crawling or URL mapping.', 'Search is the center of your product and you need broader search controls.'],
    chooseExtractor: ['You need both focused search and semantic extraction for supported platform URLs.', 'You want web, news, image, and place results under one schema-v1 contract.', 'You prefer one-credit operations, prepaid usage, and free cache hits.'],
    keywords: ['Tavily alternative', 'Tavily search API alternative', 'AI web search API', 'MCP search server', 'RAG search and extraction'],
  },
  {
    slug: 'exa',
    provider: 'Exa',
    description: 'Compare extractor.sh with Exa for neural web search, page contents, answers, research agents, and AI retrieval workflows.',
    providerStrength: 'Exa centers on web search and content retrieval, with answer, agent, Websets, and monitoring products for deeper discovery and research workflows.',
    chooseProvider: ['You need semantic or neural discovery across the web.', 'You want answer generation, research agents, monitors, or managed Websets.', 'Advanced search and discovery are more important than platform-aware entities.'],
    chooseExtractor: ['You often begin with a known public URL.', 'You need semantic product, post, profile, feed, media, or market entities for supported sources.', 'You want focused web, news, image, and place search alongside extraction.'],
    keywords: ['Exa alternative', 'Exa search API alternative', 'neural search alternative', 'AI web retrieval API', 'RAG search API'],
  },
  {
    slug: 'jina-ai-reader',
    provider: 'Jina AI Reader',
    description: 'Compare extractor.sh with Jina AI Reader for URL-to-Markdown conversion, web search, MCP, AI agents, and RAG ingestion.',
    providerStrength: 'Jina AI Reader offers model-friendly page reading and search through simple URL patterns and connects those capabilities to Jina AI’s broader retrieval tooling and MCP integrations.',
    chooseProvider: ['You prefer URL-prefix reading and search conventions.', 'You are already building with the broader Jina AI model and retrieval ecosystem.', 'General page-to-text conversion is the primary requirement.'],
    chooseExtractor: ['You need normalized schema-v1 JSON as well as Markdown.', 'You want semantic entities for supported social, commerce, app, finance, and media platforms.', 'You need dedicated web, news, image, and place endpoints with one billing model.'],
    keywords: ['Jina AI Reader alternative', 'r.jina.ai alternative', 'URL to Markdown API', 'MCP web reader', 'AI reader API'],
  },
  {
    slug: 'bright-data',
    provider: 'Bright Data',
    description: 'Compare extractor.sh with Bright Data for enterprise web scraping, browser infrastructure, proxies, datasets, and AI-ready extraction.',
    providerStrength: 'Bright Data provides a broad collection platform spanning scraper APIs, browser automation, proxy infrastructure, SERP access, unlocking, and ready-made datasets.',
    chooseProvider: ['You need enterprise proxy networks, geotargeting, or browser control.', 'You need large-scale datasets or infrastructure for difficult sites.', 'You require extensive access controls and scraping operations features.'],
    chooseExtractor: ['You need a focused developer API for public information.', 'You want clean Markdown or normalized entities rather than proxy and browser infrastructure.', 'You value simple prepaid requests and free repeated cache hits.'],
    keywords: ['Bright Data alternative', 'Bright Data scraper alternative', 'simple web extraction API', 'AI-ready scraping API', 'prepaid scraping API'],
  },
  {
    slug: 'crawl4ai',
    provider: 'Crawl4AI',
    description: 'Compare extractor.sh with Crawl4AI for open-source crawling, browser control, Markdown generation, structured extraction, and AI pipelines.',
    providerStrength: 'Crawl4AI is an open-source crawler and scraper with configurable browser control, Markdown generation, structured extraction, sessions, and self-hosted deployment options.',
    chooseProvider: ['You want to self-host and customize the complete crawler.', 'You need multi-page crawling, sessions, browser hooks, or proxy configuration.', 'You are comfortable operating extraction infrastructure.'],
    chooseExtractor: ['You want a hosted API with no crawler infrastructure to maintain.', 'You need a fast synchronous request for one URL or focused search.', 'You want platform-aware semantic entities and consistent public schemas.'],
    keywords: ['Crawl4AI alternative', 'hosted Crawl4AI alternative', 'open source scraper alternative', 'URL to Markdown API', 'AI crawler API'],
  },
  {
    slug: 'scrapegraphai',
    provider: 'ScrapeGraphAI',
    description: 'Compare extractor.sh with ScrapeGraphAI for prompt-driven extraction, scraping, search, crawling, monitoring, and AI data pipelines.',
    providerStrength: 'ScrapeGraphAI combines AI-guided scraping and structured extraction with search, crawl, and monitoring workflows driven by prompts and schemas.',
    chooseProvider: ['You need prompt-defined fields from arbitrary pages.', 'You want crawling or monitoring workflows.', 'Your output schema changes by task and AI-guided extraction is central.'],
    chooseExtractor: ['You want deterministic semantic entities for supported sources.', 'You need simple GET endpoints for extraction and focused search.', 'You prefer Markdown or stable schema-v1 JSON without defining an extraction prompt.'],
    keywords: ['ScrapeGraphAI alternative', 'AI scraping API alternative', 'prompt extraction alternative', 'structured web data API', 'RAG extraction tool'],
  },
];
